### ISSUE TITLE
unable to skip a test

### ISSUE THREAD

**Issue by sameer9900** [wiredrive/wtframework#50]
Whenever I tries to skip a test, by doing following: @unittest.skip('Bug') and then I run the test, it give following error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.5\helpers\pycharm\utrunner.py", line 151, in <module>
    TeamcityTestRunner().run(all, **options)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.5\helpers\pycharm\tcunittest.py", line 249, in run
    test(result)
  File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\suite.py", line 108, in run
    test(result)
  File "C:\Python27\lib\site-packages\unittest2\case.py", line 649, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\site-packages\wtframework\wtf\testobjects\testcase.py", line 101, in run

    self._addSkip(result, skip_why)
TypeError: _addSkip() takes exactly 4 arguments (3 given)

**Comment by dlai0001** [comment]
I think the skiptest should work.  

You might want to configure PyCharm to use NoseTest for its unittest runner.  Most of the framework is based on Nosetest.

**Comment by sameer9900** [comment]
Sorry for late reply. Problem seem to wtf framework. Whenever I am not using wtf framework, I am successfully able to skip the test. But when I am using the framework, it give me above error
