### ISSUE TITLE
unable to run ./runtests.py

### ISSUE THREAD

**Issue by bubanoid** [wiredrive/wtframework#53]
I have a problem with running the ./runtests.py
My steps form the beginning:
```
$ mkdir wtf_projects/
$ cd wtf_projects/
$ virtualenv env
$ . env/bin/activate
$ pip install wtframework
$ wtf_init.py wtf_test_project --withexamples
$ cd wtf_test_project/
$ ./runtests.py
```
and nothing happens:
```
Ran 0 tests in 0.000s
OK
```
I get the same result with running the `nosetests-2.7 tests/tests` . When I run 
```
nosetests-2.7 tests/tests/test_example.py
```
I get the following error:

> E
> ERROR: Failure: ImportError (No module named wtframework.wtf.web.page)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/tests/test_example.py", line 19, in <module>
>     from tests.flows.search_flows import perform_search
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/flows/search_flows.py", line 18, in <module>
>     from tests.pages.search_page import ISearchPage
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/pages/__init__.py", line 5, in <module>
>     from tests.pages.www_google_com import GoogleSearchPage  # @UnusedImport
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/pages/www_google_com.py", line 2, in <module>
>     from tests.pages.search_page import ISearchPage
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/pages/search_page.py", line 27, in <module>
>     import tests.pages.www_yahoo_com  # @UnusedImport
>   File "/media/win_d/Dropbox/Andriy_Work/PROJECTS/wtf_projects/wtf_test_project/tests/pages/www_yahoo_com.py", line 3, in <module>
>     from wtframework.wtf.web.page import PageObject, InvalidPageError
> ImportError: No module named wtframework.wtf.web.page
> 
> ----------------------------------------------------------------------

I suppose I am doing something totally wrong but I can not get what exactly is wrong.
Could anybody help me?

**Comment by dlai0001** [comment]
Try 'pip install -r requirements.txt'

**Comment by bubanoid** [comment]
Well... I don't fully understand what exactly should I do, as we don't have requirements.txt before `wtf_init.py wtf_test_project --withexamples` have been runned, which in it's turn can be run only after `pip install wtframework`.
So, I did the following:
```
$ mkdir wtf_projects/
$ cd wtf_projects/
$ virtualenv env && . env/bin/activate &&  pip install wtframework
$ wtf_init.py wtf_test_project --withexamples
$ deactivate
$ cd wtf_test_project/
$ virtualenv env && . env/bin/activate && pip install -r requirements.txt
$ ./runtests.py
```
and got the same result.

**Comment by bubanoid** [comment]
PS
I have noticed that my version of `wtframework` installed through `pip` is 0.4.11 whereas version presented on github is 0.4.10. Later I'll try the same with the version 0.4.10.

**Comment by dlai0001** [comment]
try doing `pip install nose` after.  I think there might be something wrong with the runtests.py script which is using nosetests-2.7 might be in the nose1 package.

**Comment by bubanoid** [comment]
`pip install nose` allowed me successfully run `nosetests-2.7 tests/tests/test_example.py`. First success! But running `nosetests-2.7 tests/tests` or `./runtests.py` still does nothing:
```
Ran 0 tests in 0.000s

OK
```
